"""MLOps catalog helpers for model lifecycle state."""

from .deployments import (
    DEPLOYMENT_STATUSES,
    MODEL_DEPLOYMENTS_TABLE_DDL,
    MODEL_DEPLOYMENTS_VIEWS_DDL,
    ModelDeploymentRecord,
    complete_deployment,
    current_online_model,
    record_deployment,
    rollback_deployment,
)
from .registry import (
    MODEL_REGISTRY_STATUSES,
    MODEL_REGISTRY_TABLE_DDL,
    MODEL_REGISTRY_VIEWS_DDL,
    ModelRegistryRecord,
    connect_mlops_db,
    current_champion,
    initialize_mlops_db,
    model_artifact_uri,
    promote_model,
    register_model,
    retire_model,
)
from .retraining import (
    CHALLENGER_TRIGGER_STATUSES,
    CHALLENGER_TRIGGERS_DDL,
    ChallengerTriggerDecision,
    RetrainingTriggerRules,
    evaluate_challenger_trigger,
    record_challenger_trigger,
    register_training_result_as_challenger,
)
from .shadow import (
    ShadowComparisonReport,
    ShadowPredictionPair,
    distribution_kl_divergence,
    distribution_wasserstein_distance,
    run_shadow_comparison,
    save_shadow_report,
)

__all__ = [
    "DEPLOYMENT_STATUSES",
    "CHALLENGER_TRIGGER_STATUSES",
    "CHALLENGER_TRIGGERS_DDL",
    "MODEL_DEPLOYMENTS_TABLE_DDL",
    "MODEL_DEPLOYMENTS_VIEWS_DDL",
    "MODEL_REGISTRY_STATUSES",
    "MODEL_REGISTRY_TABLE_DDL",
    "MODEL_REGISTRY_VIEWS_DDL",
    "ModelDeploymentRecord",
    "ModelRegistryRecord",
    "ChallengerTriggerDecision",
    "RetrainingTriggerRules",
    "ShadowComparisonReport",
    "ShadowPredictionPair",
    "complete_deployment",
    "connect_mlops_db",
    "current_online_model",
    "current_champion",
    "distribution_kl_divergence",
    "distribution_wasserstein_distance",
    "evaluate_challenger_trigger",
    "initialize_mlops_db",
    "model_artifact_uri",
    "promote_model",
    "record_deployment",
    "record_challenger_trigger",
    "register_model",
    "register_training_result_as_challenger",
    "retire_model",
    "rollback_deployment",
    "run_shadow_comparison",
    "save_shadow_report",
]
