"""Polymarket BTC Up/Down policy training package."""

from bigan.v8.polymarket.training.action_value_calibration import (
    ACTION_VALUE_CALIBRATION_SCHEMA_VERSION,
    apply_action_value_calibration,
    build_action_value_calibration_artifact,
)
from bigan.v8.polymarket.training.calibration import (
    TIME_TO_CLOSE_BUCKETS,
    calibration_report,
    split_calibration_report,
    validation_report,
)
from bigan.v8.polymarket.training.contracts import (
    ACTION_VALUE_LABEL_ACTIONS,
    AUXILIARY_OUTCOME_TARGET,
    DEFAULT_ACTION_VALUE_MODEL_VERSION,
    DEFAULT_POLICY_CREATED_AT,
    POLYMARKET_POLICY_SCHEMA_VERSION,
    POLYMARKET_POLICY_SIGNAL_SOURCE_TRAINED_MODEL,
    POLYMARKET_POLICY_TRAINING_PHASE,
    PRIMARY_POLICY_TARGET_ACTION_VALUE,
    PolymarketPolicyDataset,
    PolymarketPolicyExample,
    PolymarketPolicyModel,
    PolymarketPolicyPrediction,
    PolymarketPolicyTrainingConfig,
    PolymarketPolicyTrainingResult,
)
from bigan.v8.polymarket.training.dataset import (
    ACTION_VALUE_TARGET_FIELD,
    TARGET_LABEL_ACTION,
    dataset_profile,
    load_polymarket_policy_dataset,
)
from bigan.v8.polymarket.training.execution_layer_v2 import (
    EXECUTION_LAYER_V2_BACKTEST_MANIFEST_SCHEMA_VERSION,
    EXECUTION_LAYER_V2_BASELINE_NAME,
    EXECUTION_LAYER_V2_POLICY_NAME,
    EXECUTION_LAYER_V2_REPORT_SCHEMA_VERSION,
    EXECUTION_LAYER_V2_SCHEMA_VERSION,
    ExecutionLayerV2BacktestConfig,
    ExecutionLayerV2BacktestResult,
    ExecutionLayerV2Config,
    ExecutionLayerV2Decision,
    ExecutionLayerV2Engine,
    ExecutionLayerV2Position,
    ExecutionLayerV2Signal,
    binary_kelly_fraction,
    build_execution_layer_v2_report,
    build_execution_layer_v2_report_from_rows,
    decide_execution_layer_v2,
    execution_layer_v2_report_to_markdown,
    load_execution_layer_v2_input_rows,
    run_execution_layer_v2_backtest,
    time_decay_multiplier,
    time_decayed_kelly_notional,
)
from bigan.v8.polymarket.training.execution_layer_v2_policy_replay import (
    EXECUTION_LAYER_V2_HTS_REGIME_RISK_REPLAY_MANIFEST_SCHEMA_VERSION,
    EXECUTION_LAYER_V2_HTS_REGIME_RISK_REPLAY_SCHEMA_VERSION,
    EXECUTION_LAYER_V2_POLICY_REPLAY_MANIFEST_SCHEMA_VERSION,
    EXECUTION_LAYER_V2_POLICY_REPLAY_SCHEMA_VERSION,
    EXECUTION_LAYER_V2_RECOMMENDED_EXECUTION_POLICY_NAME,
    HTS_REGIME_RISK_POLICY_VARIANTS,
    POLICY_REPLAY_VARIANTS,
    ExecutionLayerV2HTSRegimeRiskReplayConfig,
    ExecutionLayerV2HTSRegimeRiskReplayResult,
    ExecutionLayerV2PolicyReplayConfig,
    ExecutionLayerV2PolicyReplayResult,
    build_execution_layer_v2_hts_regime_risk_replay_report,
    build_execution_layer_v2_policy_replay_report,
    execution_layer_v2_hts_regime_risk_replay_report_to_markdown,
    execution_layer_v2_policy_replay_report_to_markdown,
    run_execution_layer_v2_hts_regime_risk_replay,
    run_execution_layer_v2_policy_replay_from_settlement_csv,
)
from bigan.v8.polymarket.training.model import (
    predict_polymarket_policy_examples,
    train_polymarket_action_value_model,
    train_polymarket_probability_model,
)
from bigan.v8.polymarket.training.real_corpus_gate import (
    DEFAULT_REAL_CORPUS_MODEL_VERSION,
    DEFAULT_REAL_CORPUS_TRAINING_RUN_ID,
    POLYMARKET_REAL_CORPUS_RETRAINING_GATE_PHASE,
    POLYMARKET_REAL_CORPUS_RETRAINING_GATE_SCHEMA_VERSION,
    PolymarketRealCorpusRetrainingGateConfig,
    PolymarketRealCorpusRetrainingGateResult,
    run_polymarket_real_corpus_retraining_gate,
)


def run_polymarket_policy_training(*args, **kwargs):
    from bigan.v8.polymarket.training.runner import (
        run_polymarket_policy_training as _run_polymarket_policy_training,
    )

    return _run_polymarket_policy_training(*args, **kwargs)

__all__ = [
    "DEFAULT_POLICY_CREATED_AT",
    "POLYMARKET_POLICY_SCHEMA_VERSION",
    "POLYMARKET_POLICY_SIGNAL_SOURCE_TRAINED_MODEL",
    "POLYMARKET_POLICY_TRAINING_PHASE",
    "ACTION_VALUE_LABEL_ACTIONS",
    "AUXILIARY_OUTCOME_TARGET",
    "DEFAULT_ACTION_VALUE_MODEL_VERSION",
    "PRIMARY_POLICY_TARGET_ACTION_VALUE",
    "ACTION_VALUE_TARGET_FIELD",
    "POLYMARKET_REAL_CORPUS_RETRAINING_GATE_PHASE",
    "POLYMARKET_REAL_CORPUS_RETRAINING_GATE_SCHEMA_VERSION",
    "TARGET_LABEL_ACTION",
    "TIME_TO_CLOSE_BUCKETS",
    "ACTION_VALUE_CALIBRATION_SCHEMA_VERSION",
    "EXECUTION_LAYER_V2_BASELINE_NAME",
    "EXECUTION_LAYER_V2_BACKTEST_MANIFEST_SCHEMA_VERSION",
    "EXECUTION_LAYER_V2_HTS_REGIME_RISK_REPLAY_MANIFEST_SCHEMA_VERSION",
    "EXECUTION_LAYER_V2_HTS_REGIME_RISK_REPLAY_SCHEMA_VERSION",
    "EXECUTION_LAYER_V2_POLICY_NAME",
    "EXECUTION_LAYER_V2_POLICY_REPLAY_MANIFEST_SCHEMA_VERSION",
    "EXECUTION_LAYER_V2_POLICY_REPLAY_SCHEMA_VERSION",
    "EXECUTION_LAYER_V2_REPORT_SCHEMA_VERSION",
    "EXECUTION_LAYER_V2_RECOMMENDED_EXECUTION_POLICY_NAME",
    "EXECUTION_LAYER_V2_SCHEMA_VERSION",
    "DEFAULT_REAL_CORPUS_MODEL_VERSION",
    "DEFAULT_REAL_CORPUS_TRAINING_RUN_ID",
    "ExecutionLayerV2BacktestConfig",
    "ExecutionLayerV2BacktestResult",
    "ExecutionLayerV2Config",
    "ExecutionLayerV2Decision",
    "ExecutionLayerV2Engine",
    "ExecutionLayerV2Position",
    "ExecutionLayerV2HTSRegimeRiskReplayConfig",
    "ExecutionLayerV2HTSRegimeRiskReplayResult",
    "ExecutionLayerV2PolicyReplayConfig",
    "ExecutionLayerV2PolicyReplayResult",
    "ExecutionLayerV2Signal",
    "HTS_REGIME_RISK_POLICY_VARIANTS",
    "POLICY_REPLAY_VARIANTS",
    "PolymarketPolicyDataset",
    "PolymarketPolicyExample",
    "PolymarketPolicyModel",
    "PolymarketPolicyPrediction",
    "PolymarketPolicyTrainingConfig",
    "PolymarketPolicyTrainingResult",
    "PolymarketRealCorpusRetrainingGateConfig",
    "PolymarketRealCorpusRetrainingGateResult",
    "binary_kelly_fraction",
    "calibration_report",
    "apply_action_value_calibration",
    "build_action_value_calibration_artifact",
    "build_execution_layer_v2_report",
    "build_execution_layer_v2_report_from_rows",
    "build_execution_layer_v2_hts_regime_risk_replay_report",
    "build_execution_layer_v2_policy_replay_report",
    "dataset_profile",
    "decide_execution_layer_v2",
    "execution_layer_v2_hts_regime_risk_replay_report_to_markdown",
    "execution_layer_v2_report_to_markdown",
    "execution_layer_v2_policy_replay_report_to_markdown",
    "load_execution_layer_v2_input_rows",
    "load_polymarket_policy_dataset",
    "predict_polymarket_policy_examples",
    "run_polymarket_policy_training",
    "run_polymarket_real_corpus_retraining_gate",
    "run_execution_layer_v2_backtest",
    "run_execution_layer_v2_hts_regime_risk_replay",
    "run_execution_layer_v2_policy_replay_from_settlement_csv",
    "split_calibration_report",
    "train_polymarket_action_value_model",
    "train_polymarket_probability_model",
    "time_decayed_kelly_notional",
    "time_decay_multiplier",
    "validation_report",
]
