"""Backtest configuration and evaluation helpers."""

from .config import (
    BACKTEST_CONFIG_SCHEMA_VERSION,
    BacktestConfig,
    BacktestCostConfig,
    BacktestDatasetConfig,
    BacktestExecutionConfig,
    BacktestModelConfig,
    BacktestOutputConfig,
    BacktestStrategyConfig,
    generate_run_id,
    load_backtest_config,
)
from .data_loader import (
    LoadedClob,
    generate_synthetic_clob,
    load_clob_snapshots,
    write_clob_snapshots,
)
from .diagnostics import (
    GroupedThresholdBacktestReport,
    run_grouped_threshold_backtest,
    run_model_threshold_backtest,
    run_oracle_label_sanity_backtest,
    run_prediction_threshold_backtest,
)
from .engine import BacktestEngine, BacktestFill, BacktestResult, StrategyBacktestParams
from .evaluation import (
    CalibrationBin,
    PredictionEvaluationReport,
    ThresholdMetrics,
    evaluate_predictions,
    save_evaluation_report,
)
from .execution import (
    NoQuoteAvailableError,
    Quote,
    SimulatedTakerTrade,
    TakerExecutionSettings,
    simulate_taker_long_trade,
)
from .grid_search import (
    GridSearchReport,
    GridSearchTrial,
    apply_param_updates,
    expand_param_grid,
    run_grid_search,
    split_snapshots_by_time,
    time_series_folds,
)
from .metrics import ClosedTrade, StrategyBacktestMetrics, compute_backtest_metrics
from .strategy import (
    DEFAULT_EDGE_THRESHOLDS,
    DEFAULT_HOLD_MS,
    DEFAULT_THRESHOLDS,
    PerFamilyThresholdSelection,
    PredictionSignal,
    ThresholdStrategyResult,
    ThresholdStrategySummary,
    ThresholdTrade,
    run_per_family_threshold_search,
    run_threshold_strategy,
    run_threshold_sweep,
    save_threshold_strategy_outputs,
)
from .walk_forward import (
    MetricStability,
    WalkForwardReport,
    WalkForwardWindow,
    WalkForwardWindowResult,
    generate_walk_forward_windows,
    run_walk_forward,
    save_walk_forward_report,
    summarize_metric_stability,
)

__all__ = [
    "BACKTEST_CONFIG_SCHEMA_VERSION",
    "BacktestConfig",
    "BacktestCostConfig",
    "BacktestDatasetConfig",
    "BacktestExecutionConfig",
    "BacktestModelConfig",
    "BacktestOutputConfig",
    "BacktestStrategyConfig",
    "CalibrationBin",
    "DEFAULT_HOLD_MS",
    "DEFAULT_EDGE_THRESHOLDS",
    "DEFAULT_THRESHOLDS",
    "GroupedThresholdBacktestReport",
    "MetricStability",
    "NoQuoteAvailableError",
    "PerFamilyThresholdSelection",
    "PredictionSignal",
    "PredictionEvaluationReport",
    "Quote",
    "SimulatedTakerTrade",
    "TakerExecutionSettings",
    "ThresholdMetrics",
    "ThresholdStrategyResult",
    "ThresholdStrategySummary",
    "ThresholdTrade",
    "WalkForwardReport",
    "WalkForwardWindow",
    "WalkForwardWindowResult",
    "evaluate_predictions",
    "generate_walk_forward_windows",
    "generate_run_id",
    "load_backtest_config",
    "run_grouped_threshold_backtest",
    "run_model_threshold_backtest",
    "run_oracle_label_sanity_backtest",
    "run_prediction_threshold_backtest",
    "run_per_family_threshold_search",
    "run_walk_forward",
    "run_threshold_strategy",
    "run_threshold_sweep",
    "save_evaluation_report",
    "save_threshold_strategy_outputs",
    "save_walk_forward_report",
    "simulate_taker_long_trade",
    "summarize_metric_stability",
    "BacktestEngine",
    "BacktestFill",
    "BacktestResult",
    "ClosedTrade",
    "GridSearchReport",
    "GridSearchTrial",
    "LoadedClob",
    "StrategyBacktestMetrics",
    "StrategyBacktestParams",
    "apply_param_updates",
    "compute_backtest_metrics",
    "expand_param_grid",
    "generate_synthetic_clob",
    "load_clob_snapshots",
    "run_grid_search",
    "split_snapshots_by_time",
    "time_series_folds",
    "write_clob_snapshots",
]
